-- Set initial pizza sales tracker values
-- ⚠️ DEPRECATED - DO NOT USE THIS APPROACH
-- This file is kept for historical reference only
--
-- CORRECT APPROACH:
-- Instead of manually setting aggregate values, insert pledge records
-- for historical sales. The trigger will automatically update aggregates.
-- See: fix-pizzafunder-totals.sql
--
-- PROBLEM WITH THIS APPROACH:
-- Manually setting aggregates bypasses the pledge tracking system.
-- The trigger expects aggregates to be calculated from pledges.
-- If you set aggregates manually, they won't include actual pledges.
--
-- CORRECT METHOD:
-- 1. Insert historical pledge records (see fix-pizzafunder-totals.sql)
-- 2. Let the trigger automatically calculate totals
-- 3. Verify with: SELECT COUNT(*), SUM(pizza_count) FROM crowdfund_pledges

-- =====================================================
-- HISTORICAL CONTEXT (October 2025)
-- =====================================================
-- Initial situation:
-- - 71 pizzas, 17 backers sold before Supabase migration
-- - 32 pizzas, 6 backers sold after Supabase (in database)
-- - Solution: Inserted 17 historical pledge records totaling 71 pizzas
-- - Result: 103 total pizzas, 23 total backers
-- - Trigger continues to work for all future pledges
-- =====================================================
