services:
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - osdata:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

  web:
    image: node:20-alpine
    working_dir: /app
    command: ["sh", "-lc", "npm ci || npm install && npm run dev -- -p 3000 -H 0.0.0.0"]
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
      - OS_HOST=http://opensearch:9200
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    depends_on:
      - opensearch

  api:
    image: python:3.11-slim
    working_dir: /app
    environment:
      - OS_HOST=http://opensearch:9200
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: ["bash", "-lc", "pip install -r requirements.txt && uvicorn api.main:app --host 0.0.0.0 --port 8000"]
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - opensearch

volumes:
  osdata:
