import PriceUsdInput from '../components/PriceUsdInput.jsx'

export default {
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    { name: 'title', title: 'Title', type: 'string', validation: (Rule) => Rule.required() },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title', maxLength: 96 } },
    { name: 'shortDescription', title: 'Short Description', type: 'string' },
    { name: 'longDescription', title: 'Long Description (Portable Text)', type: 'array', of: [{ type: 'block' }] },
    { name: 'images', title: 'Images', type: 'array', of: [{ type: 'image' }], options: { layout: 'grid' } },
    { name: 'price', title: 'Price (USD)', description: 'Enter dollars (USD).', type: 'number', components: { input: PriceUsdInput }, validation: (Rule) => Rule.min(0) },
    { name: 'salePrice', title: 'Sale Price (USD)', description: 'Optional sale price in dollars (USD).', type: 'number', components: { input: PriceUsdInput } },
    { name: 'priceDisplay', title: 'Price Display Override', type: 'string', description: 'Optional text shown instead of formatted price (e.g., "$8 pre-order").' },
    { name: 'currency', title: 'Currency', type: 'string', initialValue: 'USD', readOnly: true },
    { name: 'squareItemId', title: 'Square Item ID', type: 'string' },
    { name: 'squareVariationId', title: 'Square Variation ID', type: 'string' },
    {
      name: 'variants',
      title: 'Variants (optional)',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          { name: 'name', type: 'string', title: 'Name' },
          { name: 'squareVariationId', type: 'string', title: 'Square Variation ID' },
          { name: 'price', type: 'number', title: 'Price (USD)', description: 'Enter dollars (USD).', components: { input: PriceUsdInput } },
        ]
      }]
    },
    {
      name: 'squareCheckoutLinkUrl',
      title: 'Square Checkout Link URL',
      type: 'url',
      description: 'Tier A: direct checkout link generated by Square.'
    },
    {
      name: 'inventoryMode',
      title: 'Inventory Mode',
      type: 'string',
      initialValue: 'unmanaged',
      options: {
        list: [
          { title: 'Unmanaged / Infinite', value: 'unmanaged' },
          { title: 'Square Managed', value: 'square' },
          { title: 'Manual (enter quantity)', value: 'manual' }
        ],
        layout: 'radio'
      }
    },
    {
      name: 'manualQty',
      title: 'Manual Inventory Quantity',
      type: 'number',
      hidden: ({ parent }) => parent?.inventoryMode !== 'manual',
      validation: (Rule) => Rule.min(0)
    },
    {
      name: 'lastSyncedAt',
      title: 'Last Synced At',
      type: 'datetime',
      readOnly: true,
      description: 'Timestamp of last sync from Square or other systems.'
    },
    { name: 'tags', title: 'Tags', type: 'array', of: [{ type: 'string' }] },
    { name: 'active', title: 'Active', type: 'boolean', initialValue: true },
  ],
  preview: {
    select: { title: 'title', media: 'images.0' },
  },
}
