// Default weekly schedule data for the kanban planner.
// Each card has a unique id, day assignment, zone, and financial metadata.

let _nextId = 1;
const id = () => String(_nextId++);

export const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export const PEOPLE = ['Weston', 'Catherine', 'Teddy'];

// Fractional ordering: cards start at 1, 2, 3... within each day+zone.
// On reorder we compute midpoints; no DB needed.

export function createDefaultCards() {
  _nextId = 1;
  return [
    // ── Monday ──────────────────────────────────────────
    {
      id: id(),
      title: 'Cook',
      day: 'Monday',
      zone: 'timed',
      people: ['Weston', 'Catherine'],
      startTime: '07:00',
      endTime: '16:00',
      revenue: 450,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },
    {
      id: id(),
      title: 'Babysitter for Teddy',
      day: 'Monday',
      zone: 'timed',
      people: ['Teddy'],
      startTime: '08:00',
      endTime: '14:00',
      revenue: 0,
      cost: 0, // computed: $20/hr × duration
      costPerHour: 20,
      optional: true,
      enabled: false,
      effectTarget: null,
      effectType: null,
      order: 2,
    },

    // ── Tuesday ─────────────────────────────────────────
    {
      id: id(),
      title: 'Catherine off with Teddy',
      day: 'Tuesday',
      zone: 'untimed',
      people: ['Catherine', 'Teddy'],
      startTime: null,
      endTime: null,
      revenue: 0,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },
    {
      id: id(),
      title: 'Admin',
      day: 'Tuesday',
      zone: 'timed',
      people: ['Weston'],
      startTime: '10:00',
      endTime: '18:00',
      revenue: 0,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },

    // ── Wednesday ───────────────────────────────────────
    {
      id: id(),
      title: 'Cook',
      day: 'Wednesday',
      zone: 'timed',
      people: ['Weston', 'Catherine'],
      startTime: '07:00',
      endTime: '10:00',
      revenue: 200,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },
    {
      id: id(),
      title: 'Substitute cook',
      day: 'Wednesday',
      zone: 'timed',
      people: [],
      startTime: '07:00',
      endTime: '10:00',
      revenue: 0,
      cost: 0,
      costPerHour: 35,
      optional: true,
      enabled: false,
      effectTarget: null,
      effectType: null,
      order: 2,
    },

    // ── Thursday ────────────────────────────────────────
    {
      id: id(),
      title: 'Catherine off with Teddy',
      day: 'Thursday',
      zone: 'untimed',
      people: ['Catherine', 'Teddy'],
      startTime: null,
      endTime: null,
      revenue: 0,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },
    {
      id: id(),
      title: 'Pizza',
      day: 'Thursday',
      zone: 'timed',
      people: ['Weston'],
      startTime: '10:00',
      endTime: '14:00',
      revenue: 200,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },
    {
      id: id(),
      title: 'Second cook',
      day: 'Thursday',
      zone: 'timed',
      people: [],
      startTime: '10:00',
      endTime: '14:00',
      revenue: 0,
      cost: 0,
      costPerHour: 35,
      optional: true,
      enabled: false,
      // When enabled, doubles the pizza card's revenue
      effectTarget: '8', // id of Thursday Pizza card
      effectType: 'double_revenue',
      order: 2,
    },

    // ── Friday ──────────────────────────────────────────
    {
      id: id(),
      title: 'Cook',
      day: 'Friday',
      zone: 'timed',
      people: ['Weston', 'Catherine'],
      startTime: '06:00',
      endTime: '10:00',
      revenue: 200,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },
    {
      id: id(),
      title: 'Babysitter for Teddy',
      day: 'Friday',
      zone: 'timed',
      people: ['Teddy'],
      startTime: '06:00',
      endTime: '10:00',
      revenue: 0,
      cost: 0,
      costPerHour: 20,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 2,
    },
    {
      id: id(),
      title: 'Store work',
      day: 'Friday',
      zone: 'timed',
      people: ['Catherine'],
      startTime: '11:00',
      endTime: '16:00',
      revenue: 125,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 3,
    },
    {
      id: id(),
      title: 'Teddy with Weston',
      day: 'Friday',
      zone: 'untimed',
      people: ['Weston', 'Teddy'],
      startTime: null,
      endTime: null,
      revenue: 0,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },

    // ── Saturday ────────────────────────────────────────
    // No scheduled work — lane stays empty

    // ── Sunday ──────────────────────────────────────────
    {
      id: id(),
      title: 'Cook',
      day: 'Sunday',
      zone: 'timed',
      people: ['Weston'],
      startTime: '10:00',
      endTime: '18:00',
      revenue: 200,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 1,
    },
    {
      id: id(),
      title: 'Second cook',
      day: 'Sunday',
      zone: 'timed',
      people: [],
      startTime: '10:00',
      endTime: '18:00',
      revenue: 0,
      cost: 0,
      costPerHour: 35,
      optional: true,
      enabled: false,
      effectTarget: '14', // id of Sunday Cook card
      effectType: 'double_revenue',
      order: 2,
    },
    {
      id: id(),
      title: 'Store work',
      day: 'Sunday',
      zone: 'timed',
      people: ['Catherine'],
      startTime: '07:30',
      endTime: '15:00',
      revenue: 150,
      cost: 0,
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 3,
    },
    {
      id: id(),
      title: 'Babysitter for Teddy',
      day: 'Sunday',
      zone: 'timed',
      people: ['Teddy'],
      startTime: '09:00',
      endTime: '15:00',
      revenue: 0,
      cost: 0,
      costPerHour: 0, // Free on Sunday
      optional: false,
      enabled: true,
      effectTarget: null,
      effectType: null,
      order: 4,
    },
  ];
}
